feat(assets): extract all assets into a folder
renovatebot/tutorial pull request #35
Opened 2023-08-17 11:36 UTC by Gabriel-Ladzaretti

context 
 - https://github.com/renovatebot/tutorial/pull/28#discussion_r1282399158

2023-08-17 11:37 UTC, Gabriel-Ladzaretti commented
@HonkingGoose

2023-08-21 09:10 UTC, HonkingGoose requested changes

2023-08-21 09:10 UTC, HonkingGoose commented on .gitignore
> +.idea
GitHub has a repository with good gitignore templates. They have a [`.gitignore` template for Jetbrains IDE's](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore).

Maybe we should copy/paste some things from them? Before copying, check if their license is okay for us: [`github/gitignore` license file](https://github.com/github/gitignore/blob/main/LICENSE).

2023-08-21 09:10 UTC, HonkingGoose commented on assets/change-in-config-1.png
We should use plain JSON text instead of a screenshot.

2023-08-21 09:10 UTC, HonkingGoose commented on assets/pending-approval-config.png
This screenshot should be converted to plain text JSON.

2024-03-11 21:08 UTC, closed without merging